name: kantin_jawara
description: "Aplikasi Kantin Jawara - Solusi untuk Kantin Untirta yang ramai"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

  # State Management
  get: ^4.6.6

  # Network & API
  http: ^1.4.0

  # Storage
  shared_preferences: ^2.5.3

  # Media & Permissions
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  url_launcher: ^6.3.2
  package_info_plus: ^8.3.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/image/logokantinjawara.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/image/logokantinjawara.png"
